#!/bin/python
import os
import sys
from pathlib import Path
import subprocess


if(len(sys.argv) < 2):
    print("😞 Missing wallpaper path")
    exit(1)

wallpaper_path = Path(sys.argv[1])

if os.fork() == 0:
    subprocess.run(f"magick {wallpaper_path} ~/.config/hypr/wallpaper.png",shell=True, stdout=subprocess.DEVNULL)
    subprocess.run("killall -9 hyprpaper",shell=True, stdout=subprocess.DEVNULL)
    subprocess.run(f"hyprpaper unload {wallpaper_path}", shell=True, stdout=subprocess.DEVNULL)
    subprocess.run("hyprpaper", shell=True, stdout=subprocess.DEVNULL)

exit(0)
